### ISSUE TITLE
no configure script in user/libpcap/libpcap-1.3.0

### ISSUE THREAD

**Issue by valerio-click** [pfq/PFQ#11]
I wanted to test PFQ's libpcap but in user/libpcap/libpcap-1.3.0 there is no configure script as expected by reading the INSTALL.txt.

Is it possible to test PFQ on libpcap 1.7.4? 

regards,
Valerio

**Comment by awgn** [comment]
You need to use the GNU auto tools the generate it.

Why the new pcap? What's the difference with pcap 1.3?

N.
