### ISSUE TITLE
pfq_read_linux hangs on suricata and bro

### ISSUE THREAD

**Issue by Mr-Click** [pfq/PFQ#14]
I tested PFQ (both master and experimantel branch) with modified pcap libraries (1.3.0 and 1.7.4) on suricata (with autofp mode) and bro. In both test cases (using iface pfq:ethX) pfq_read_linux hangs in the following loop:

for(; (max_packets <= 0 || n > 0) && (it != it_end); it = pfq_net_queue_next(&nq, it))
{
   ...
         while (!pfq_pkt_ready(&nq, it))
	 pfq_yield();
   ...
If suricata is executed in worker mode the library seems to work properly.

regards,
Valerio

**Comment by awgn** [comment]
Hi Valerio,

PFQ has not been tested yet with Suricata, and I'm not familiar with autofp mode or with worker mode.
Please send me a detailed email so I can understand and fix the problem.

Thanks,
N.

**Comment by Mr-Click** [comment]
HI Nicola,

I confirm you that with the new commits the issue has been solved!!
I suggest to add in the wiki how to reserve Hugepages and which env variable is necessary to specify for PFQ to use the standard 4k size.

regards,
Valerio

**Comment by awgn** [comment]
:+1:
