### ISSUE TITLE
pfq-gen: PFQ: Tx bind error: Device or resource busy

### ISSUE THREAD

**Issue by emmericp** [pfq/PFQ#18]
Hi,

any idea what might be causing this? pfq-gen without -k and -a works fine

    # pfq-gen --rate 2 -t 0.0.eth4 -k 0 -l 60 -a
    device     : dev{eth4}
    rand_ip    : false
    len        : 60
    flush-hint : 1
    copies     : 1
    rate       : 2 Mpps
    thread     : 0 -> thread_binding{cpu:0 gid:0 dev{eth4 [0]}} kthread { 0 }
    pfq-gen: PFQ: Tx bind error: Device or resource busy

    # ./test-send eth4 0 0 10
    PFQ: Tx bind error
    # ./test-send++ eth4 0 0 10
    PFQ: Tx bind error: Device or resource busy

    # dmesg
    [4937334.855992] [PFQ|0] could not bind Tx[0] thread: resource busy!

    # uname -r
    3.16.0-30-generic

    # lsb_release  -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.2 LTS
    Release:	14.04
    Codename:	trusty

ixgbe-3.22.3 compiled with pfq-omatic
PFQ version: we tried both master and v5.2

 Paul

**Comment by emmericp** [comment]
Nevermind, fixed it.

Setting tx_affinity explicitly for the kernel module solved it. Found it by adding a debug message in pfq_bind_tx_thread(). Maybe "busy" is not the best error message here.

I never needed to set the tx_affinity option explicitly before, dunno why this issue suddenly appeared.

**Comment by awgn** [comment]
Hi Paul. This is a major update. 

It allows to specify at insmod/time the number of in-kernel Tx threads (and the cores where they run) with the tx_affinity option (e.g. tx_affinity=3,4,5 enables 3 kernel threads on core 3, 4 and 5). This is a system-wide option, in my opinion superior to let the application fires a kernel thread on a certain core at will.

Yet, the library has been updated with additional APIs: send, send_to, send_async and send_at... and it's noteworthy possibile, unlike before, to use the same kernel thread to transmit packets from multiple sockets/applications :-)

**Comment by emmericp** [comment]
Can you maybe add the tx_affinity option to the example config file?
It was quite confusing for us that the example config stopped working after upgrading

**Comment by awgn** [comment]
Paul, I've just re-open the issue.

To be sure it's not a bug I'll try to figure out what's going on (asap) and if not, I'll update the documentation/examples accordingly.

Thanks for reporting.
N.

**Comment by awgn** [comment]
Paul,

I have just updated the two functions involved, improving both error messages and error codes.
I also updated the pfq.example.conf file, accordingly.

I can close the ticket now.
N.
