### ISSUE TITLE
PFQ: get id error: Protocol not available

### ISSUE THREAD

**Issue by luongnv89** [pfq/PFQ#26]
Hi,
I have installed `PFQ` successfully. However I have some problem when starting `pfq-gen`.

```
~$ pfq-load 
Using default config...
Irqbalance daemon detected @pid [1331]. Sending SIGKILL...
Loading pfq...
-> /sbin/modprobe pfq 
Setting irq affinity...
PFQ ready.
~$ pfq-gen -t 0.5.eth1
device     : dev{eth1}
*** Warning: HugePages not mounted ***
rand_ip    : false
len        : 1514
flush-hint : 1
copies     : 1
pfq-gen: PFQ: get id error: Protocol not available
```

I am using Ubuntu:

```
~$ uname -a
Linux lab7-ProLiant-DL360-G5 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Do you have any document about how to setup, test and use PFQ API in an application?
Thank you very much for a great project

**Comment by pfq** [comment]
Hu Nguyen,

First of all thanks for reporting. You can start from here:
https://github.com/pfq/PFQ/wiki

The problem you mentioned relates to the current master branch, isn't it?

Not sure what's going on there, because that's a typical error you occur
when running a C++ application without loading the kernel module.
Are you sure that everything is fine? E.g. The kernel module is effectively
loaded?

Thanks,
N.

**Comment by luongnv89** [comment]
@pfq yes, I am testing on `master` branch.
In fact I am not sure that `everything is fine` since I do not know how to check that. 
My `pfq.conf` as bellow:
```
    Config {
        pfq_module = "[PATH_TO]/PFQ/kernel/pfq.ko",
        pfq_options = ["capture_incoming=0", "capt_batch_len=32", "xmit_batch_len=128", "skb_pool_size=256"],
        exclude_core = [],
            irq_affinity = ["round-robin"],
            drivers = [
                Driver {
                    drvmod = "/lib/modules/3.13.0-24-generic/kernel/drivers/net/ethernet/intel/ixgbe/ixgbe.ko",
                    drvopt = ["LRO=0,0", "DCA=1,1", "AtrSampleRate=0,0"],
                        devices = [
                            Device {
                                devname = "eth1",
                                    devspeed = Just 10000,
                                    flowctrl = No,
                                    ethopt = [("-G", "tx", 768),
                                        ("-C", "tx-frames-irq", 1024),
                                        ("-C", "rx-usecs", 50)
                                    ]

                            }

                        ]
                }
            ]
    }

```

I am testing on the network interfaces `eth1` . The detail information of the network interfaces:

```
$ ethtool -i eth1
driver: ixgbe
version: 3.15.1-k
firmware-version: 0x8000037c
bus-info: 0000:0b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no
```

This time I have tried to use `pfq-load` with my configuration file, and there was an error:

```
$ pfq-load -c pfq.conf -q 3
Using pfq.conf config...
Unloading pfq...
-> /sbin/rmmod pfq
pfq-load: Prelude.read: no parse
```

So I guess the problem might come from the fact that the `pfq kernel module was not actually loaded`. But I do not know how to fix this?

Thank you for your help
