### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [pfq/PFQ#3]
I would like to point out that identifiers like "[```_PF_Q_ENGINE_H_```](https://github.com/pfq/PFQ/blob/4cc1a36e65b284ffb26a056f3bc32a6fc3697172/kernel/pf_q-engine.h#L25)" and "[```_PF_Q_MODULE_H_```](https://github.com/pfq/PFQ/blob/1a6e61489c474babbb40df76383473d1821e6ca7/kernel/pf_q-module.h#L24)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by awgn** [comment]
The Linux kernel is full of guard macro declared that way. However I'll update them in the next release. Thanks
