### ISSUE TITLE
libpcap-fanout returns error when capturing from non pfq interface

### ISSUE THREAD

**Issue by sergico** [pfq/PFQ#30]
Hi, 
I'm trying to capture packets using the libpcap-fanout and tcpdump.
When caputuring using the non pfq interface naming (i.e. pfq:eth0) I got the following error:

```
# tcpdump -n -s 64 -v eth7 udp
tcpdump: snaplen of 0 rejects all packets
```

Is this the expected behaviour? That is: libpcap fanout allows to capture packet only from the pfq-enabled interfaces?

Thanks
Sergio

**Comment by awgn** [comment]
No,

It is not the expected behavior, unless another PFQ socket has already
taken over the control of the same port...

Is this your case?

N.

**Comment by sergico** [comment]
Not sure actually. 
Let me do a quick check...

Thanks
Sergio

**Comment by sergico** [comment]
I run again the above command ensuring no other processes on the host are using pfq sockets but I'm getting the same error.
Also tried setting the PFQ_CAPLEN environment variable to 64, but still getting the same error message:

```
root@iqac-101250:/opt/agent/lib/pfq# export PFQ_CAPLEN=64
root@iqac-101250:/opt/agent/lib/pfq# echo $PFQ_CAPLEN 
64
root@iqac-101250:/opt/agent/lib/pfq# tcpdump -n -s64 -v -i eth7 udp
tcpdump: snaplen of 0 rejects all packets

```

**Comment by awgn** [comment]
The default configuration values are not correctly loaded when PCAP_CONFIG is not specified.

**Comment by awgn** [comment]
The bug is fixed now.
