### ISSUE TITLE
linking issue - multiple definition of pfq::lang::funptr

### ISSUE THREAD

**Issue by grzryc** [pfq/PFQ#31]
Hi.
I run into a problem:
when linking multiple .o files that reference <pfq/pfq.hpp> linker (gcc 6.3) complaints about multiple definitions of pfq::lang::funptr
I created a [repo]( https://github.com/grzryc/pfq-linker-issue) for ease of reproduction 
When building with `make`
i get following result 
```g++ -Wall -o test test.o dummy.o -lpfq
dummy.o:(.bss+0x0): multiple definition of pfq::lang::funptr
test.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
```

**Comment by awgn** [comment]
Thanks for reporting anonymous user...
