### ISSUE TITLE
Paper link is dead

### ISSUE THREAD

**Issue by bullno1** [pfq/PFQ#33]
Not really a code issue but I have never been able to read the paper at: http://tma2012.ftw.at/papers/PAM2012paper12.pdf (from README)

**Comment by CMCDragonkai** [comment]
Would be nice if there was some documentation on how to use this too.

**Comment by yoskini** [comment]
Good morning,

please have a look at the wiki page available from here <https://github.com/pfq/PFQ/wiki>.
In addition, try looking at C++ and Haskell examples available from here <https://github.com/pfq/PFQ/tree/master/user/pfq-tools> and here <https://github.com/pfq/PFQ/tree/master/user/pfq-hcounters> respectively.
pfq-lang examples <https://github.com/pfq/PFQ/tree/master/user/pfq-lang/examples> are available as well.

Best regards,

Fabio

**Comment by awgn** [comment]
Sorry for the delay guys. Links to the conference proceedings and paper have been fixed.
