### ISSUE TITLE
Compilation on `3.16.0-4-amd64` fails

### ISSUE THREAD

**Issue by tolysz** [pfq/PFQ#4]
`Linux wthing 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux`

    make -C /lib/modules/3.16.0-4-amd64/build M=/home/m/workHS/github/PFQ/kernel modules
    make[1]: Entering directory '/usr/src/linux-headers-3.16.0-4-amd64'
    Makefile:10: *** mixed implicit and normal rules: deprecated syntax
    make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-amd64'
      CC [M]  /home/m/workHS/github/PFQ/kernel/pf_q.o
    In file included from /home/m/workHS/github/PFQ/kernel/pf_q.c:66:0:
    /home/m/workHS/github/PFQ/kernel/pf_q-vlan.h: In function ‘pfq_vlan_untag’:
    /home/m/workHS/github/PFQ/kernel/pf_q-vlan.h:39:9: error: implicit declaration of function ‘vlan_untag’ [-Werror=implicit-function-declaration]
             return vlan_untag(skb);
             ^
    /home/m/workHS/github/PFQ/kernel/pf_q-vlan.h:39:9: warning: return makes pointer from integer without a cast [enabled by default]
    /home/m/workHS/github/PFQ/kernel/pf_q.c: At top level:
    /home/m/workHS/github/PFQ/kernel/pf_q.c:120:9: note: #pragma message: [PFQ] *** using extended proc ***
     #pragma message "[PFQ] *** using extended proc ***"
             ^
    /home/m/workHS/github/PFQ/kernel/pf_q.c:123:9: note: #pragma message: [PFQ] *** PFQ_DEBUG mode ***
     #pragma message "[PFQ] *** PFQ_DEBUG mode ***"
             ^
    /home/m/workHS/github/PFQ/kernel/pf_q.c:126:9: note: #pragma message: [PFQ] *** DEBUG mode ***
     #pragma message "[PFQ] *** DEBUG mode ***"
             ^
    cc1: some warnings being treated as errors
    /usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:262: recipe for target '/home/m/workHS/github/PFQ/kernel/pf_q.o' failed
    make[4]: *** [/home/m/workHS/github/PFQ/kernel/pf_q.o] Error 1
    /usr/src/linux-headers-3.16.0-4-common/Makefile:1350: recipe for target '_module_/home/m/workHS/github/PFQ/kernel' failed
    make[3]: *** [_module_/home/m/workHS/github/PFQ/kernel] Error 2
    Makefile:181: recipe for target 'sub-make' failed
    make[2]: *** [sub-make] Error 2
    Makefile:8: recipe for target 'all' failed
    make[1]: *** [all] Error 2
    make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
    Makefile:39: recipe for target 'all' failed
    make: *** [all] Error 2

`ghc -v`

    Glasgow Haskell Compiler, Version 7.8.4, stage 2 booted by GHC version 7.4.1
    Using binary package database: /home/m/ghc/lib/ghc-7.8.4/package.conf.d/package.cache
    Using binary package database: /home/m/.ghc/x86_64-linux-7.8.4/package.conf.d/package.cache
    hiding package transformers-0.3.0.0 to avoid conflict with later version transformers-0.4.2.0
    hiding package Cabal-1.18.1.5 to avoid conflict with later version Cabal-1.22.0.0
    hiding package mtl-2.1.3.1 to avoid conflict with later version mtl-2.2.1
    hiding package Cabal-1.20.0.3 to avoid conflict with later version Cabal-1.22.0.0
    wired-in package ghc-prim mapped to ghc-prim-0.3.1.0-a24f9c14c632d75b683d0f93283aea37
    wired-in package integer-gmp mapped to integer-gmp-0.5.1.0-26579559b3647acf4f01d5edd9491a46
    wired-in package base mapped to base-4.7.0.2-bfd89587617e381ae01b8dd7b6c7f1c1
    wired-in package rts mapped to builtin_rts
    wired-in package template-haskell mapped to template-haskell-2.9.0.0-6d27c2b362b15abb1822f2f34b9ae7f9
    wired-in package dph-seq not found.
    wired-in package dph-par not found.

`gcc -v`

    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v 
       --with-pkgversion='Debian 4.9.2-7' 
       --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs 
       --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ 
       --prefix=/usr 
       --program-suffix=-4.9 
       --enable-shared 
       --enable-linker-build-id
       --libexecdir=/usr/lib 
       --without-included-gettext 
       --enable-threads=posix 
       --with-gxx-include-dir=/usr/include/c++/4.9 
       --libdir=/usr/lib --enable-nls 
       --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes 
       --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib 
       --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo 
       --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home 
       --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64
       --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar
       --enable-objc-gc --enable-multiarch --    with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32
       --enable-multilib --with-tune=generic --enable-checking=release
       --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 4.9.2 (Debian 4.9.2-7)

**Comment by awgn** [comment]
Hi tolysz,

The function vlan_untag has been renamed to skb_vlan_untag starting from kernel 3.17. However Debian Jessie, for a period, was distributing a kernel 3.16 with the function already renamed. That was causing the problem. If you dist upgrade your Jessie everything should be fine.

**Comment by tolysz** [comment]
You are a star :)
But I can not update my kernel... there is no kbuild-3.18 nor image-3.17... so I am stuck, however they patched my kernel.... so the only think I had to do was modify line 34 `pf_q-vlan.h ` from 17 to 16 :D

    #elif (LINUX_VERSION_CODE < KERNEL_VERSION(3,16,0))

**Comment by awgn** [comment]
Yep right... I'm trying to find a general fix to this, with no luck for now. However I close the issue :+1:
